### ISSUE TITLE
Could not pass PlayerJoinEvent

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Finale#12]
[02:46:16] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Finale v2.0.0-SNAPSHOT
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/util/CraftChatMessage
	at vg.civcraft.mc.civmodcore.chat.ChatUtils.stringify(ChatUtils.java:304) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at vg.civcraft.mc.civmodcore.inventory.items.PotionUtils.getEffectNiceName(PotionUtils.java:100) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at com.github.maxopoly.finale.overlay.ScoreboardHUD.updateAllPotionEffects(ScoreboardHUD.java:177) ~[Finale-paper-2.0.0-SNAPSHOT.jar:?]
	at com.github.maxopoly.finale.overlay.ScoreboardHUD.playerJoin(ScoreboardHUD.java:141) ~[Finale-paper-2.0.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor243.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-333]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.util.CraftChatMessage
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 20 more

**Comment by wingzero54** [comment]
Appears to have been due to outdated CivModCore, unrelated to combat issues
