### ISSUE TITLE
Task #59 exception

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Finale#13]
[02:46:16] [Server thread/WARN]: [Finale] Task #59 for Finale v2.0.0-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/util/CraftChatMessage
	at vg.civcraft.mc.civmodcore.chat.ChatUtils.stringify(ChatUtils.java:304) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at vg.civcraft.mc.civmodcore.inventory.items.PotionUtils.getEffectNiceName(PotionUtils.java:100) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
	at com.github.maxopoly.finale.overlay.ScoreboardHUD.updateAllPotionEffects(ScoreboardHUD.java:177) ~[Finale-paper-2.0.0-SNAPSHOT.jar:?]
	at com.github.maxopoly.finale.overlay.ScoreboardHUD.lambda$new$0(ScoreboardHUD.java:50) ~[Finale-paper-2.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-333]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.util.CraftChatMessage
	... 12 more

**Comment by wingzero54** [comment]
Appears to have been due to outdated CivModCore, unrelated to combat issues
