### ISSUE TITLE
Task #1658 Exception

### ISSUE THREAD

**Issue by nebula161** [CivMC/Finale#14]
`[23:23:03 WARN]: [Finale] Task #1658 for Finale v2.0.0-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/util/CraftChatMessage
        at vg.civcraft.mc.civmodcore.chat.ChatUtils.stringify(ChatUtils.java:304) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
        at vg.civcraft.mc.civmodcore.inventory.items.PotionUtils.getEffectNiceName(PotionUtils.java:100) ~[CivModCore-paper-2.0.0-SNAPSHOT.jar:?]
        at com.github.maxopoly.finale.overlay.ScoreboardHUD.updateAllPotionEffects(ScoreboardHUD.java:177) ~[Finale-paper-2.0.0-SNAPSHOT.jar:?]
        at com.github.maxopoly.finale.overlay.ScoreboardHUD.lambda$new$0(ScoreboardHUD.java:50) ~[Finale-paper-2.0.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.util.CraftChatMessage
        ... 12 more`
Related to potion effects. Got this immediately after buffing up in pvp

**Comment by Diet-Cola** [comment]
Potentially outdated version since mentions 1.18.1?
