### ISSUE TITLE
Finale throws error when player melee hits mobs and players

### ISSUE THREAD

**Issue by nebula161** [CivMC/Finale#25]
`[15:24:50 WARN]: [Finale] Task #180741 for Finale v2.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Iterator.next()" is null
        at com.github.maxopoly.finale.combat.CPSHandler.getCPS(CPSHandler.java:46) ~[finale-paper-2.0.2.jar:?]
        at com.github.maxopoly.finale.combat.AsyncPacketHandler$1.run(AsyncPacketHandler.java:100) ~[finale-paper-2.0.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Doesn't occur upon breaking minecarts, makes the particles for the player who's hitting but no-one else
Doesn't combat tag
Doesn't affect the same player across accounts

**Comment by Diet-Cola** [comment]
Is this with any specific config settings or just a fresh install of Finale?

**Comment by Aleksey-Terzi** [comment]
I think the problem happened because we get access to the list: https://github.com/CivMC/Finale/blob/master/paper/src/main/java/com/github/maxopoly/finale/combat/CPSHandler.java#L40

But this list can be used in different threads and this list is not synchronized.
I guess we should use here concurrent queue instead.
