### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Finale#34]
[09:19:53] [Server thread/WARN]: [Finale] Task #2717920 for Finale v2.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getType()" because "entity" is null
	at com.github.maxopoly.finale.combat.AsyncPacketHandler$1.run(AsyncPacketHandler.java:85) ~[finale-paper-2.0.2.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by Diet-Cola** [comment]
Potentially Fixed by #33
